
baseURL = "https://www.fiveheaps.com"
languageCode = "en-us"
title = "Five Heaps"
theme = "clotho"
enableEmoji = true

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = "UA-162013108-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = ""
  recent_posts_number = 2

[params.utterances]
  isEnabled = true
  issueTerm= "pathname"
  repo = "genshinh/five-heaps-metadata"
  theme = "github-light"
